authToken:
  maxTokenLength: 128

user:
  maxUsernameLength: 32
  minPasswordLength: 8
  maxPasswordLength: 72
  passwordHashRounds: 10
  maxNameLength: 16

category:
  maxNameLength: 16

article:
  defaultQueryLimit: 30
  maxQueryLimit: 30
  defaultThumbnailUrl: ""
  maxThumbnailUrlLength: 2048
  maxThumbnailCaptionLength: 64
  maxTitleLength: 64
  maxSubtitleLength: 128
  maxContentDeltaLength: 10000

uploads:
  tempPath: "./uploads/tmp"

thumbnail:
  path: "./uplaods/thumbnails"
  width: 600
  height: 400
  maxBytes: 4194304

image:
  path: "./uploads/images"
  maxBytes: 4194304
  supportedFormats:
    - jpeg
    - png
    - webp
