name: Build and Test Docker Images

on:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend
        run: docker build -f frontend/Dockerfile ./frontend

      - name: Build Backend
        run: docker build -f backend/Dockerfile ./backend
